// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsF3J_DdGGqbKIGW8mKAvjS1-oC94ViXU',
    appId: '1:639068244751:web:061730ddc0bc05c081cc7a',
    messagingSenderId: '639068244751',
    projectId: 'ternak-44861',
    authDomain: 'ternak-44861.firebaseapp.com',
    storageBucket: 'ternak-44861.appspot.com',
    measurementId: 'G-P2QGFCTGSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZDV6UDu0mpjSw9TjKDE_kEUqtEyFdLo',
    appId: '1:639068244751:android:b200b24aed34f05f81cc7a',
    messagingSenderId: '639068244751',
    projectId: 'ternak-44861',
    storageBucket: 'ternak-44861.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRu02mZGmpoJE-2D2GhtL9NAEMHlK1Zpk',
    appId: '1:639068244751:ios:5da55fb9f3c33a8381cc7a',
    messagingSenderId: '639068244751',
    projectId: 'ternak-44861',
    storageBucket: 'ternak-44861.appspot.com',
    iosBundleId: 'com.example.ternak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRu02mZGmpoJE-2D2GhtL9NAEMHlK1Zpk',
    appId: '1:639068244751:ios:5da55fb9f3c33a8381cc7a',
    messagingSenderId: '639068244751',
    projectId: 'ternak-44861',
    storageBucket: 'ternak-44861.appspot.com',
    iosBundleId: 'com.example.ternak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsF3J_DdGGqbKIGW8mKAvjS1-oC94ViXU',
    appId: '1:639068244751:web:92755bddb2bfca3681cc7a',
    messagingSenderId: '639068244751',
    projectId: 'ternak-44861',
    authDomain: 'ternak-44861.firebaseapp.com',
    storageBucket: 'ternak-44861.appspot.com',
    measurementId: 'G-SPGZLJR6Y8',
  );
}
